[package]
name = "fstapi"
version = "0.0.1"
authors = ["MaxXing <x@MaxXSoft.net>"]
edition = "2021"
description = "API for Fast Signal Trace format files."

[dependencies]

[build-dependencies]
bindgen = "0.64.0"
