name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_test:
    name: Build and Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Install Required Packages (Windows)
      if: runner.os == 'Windows'
      run: |
        vcpkg install zlib:x64-windows-static-md
        vcpkg install pthreads:x64-windows-static-md
        vcpkg install mman:x64-windows-static-md

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Rust Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cargo check && cargo check --all-features

    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Format
      run: cargo fmt --all --check

    - name: Test
      run: cargo test --workspace
